// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -466332677;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_local_dart_scorer',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiBridgeThingdBridgeAppendEvent({
    required ThingdBridge that,
    required String stream,
    required String eventType,
    required String body,
  });

  Future<String?> crateApiBridgeThingdBridgeDeleteLastEvent({
    required ThingdBridge that,
    required String stream,
  });

  Future<bool> crateApiBridgeThingdBridgeDeleteObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  });

  Future<BigInt> crateApiBridgeThingdBridgeDeleteStream({
    required ThingdBridge that,
    required String stream,
  });

  Future<String?> crateApiBridgeThingdBridgeGetObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  });

  Future<List<String>> crateApiBridgeThingdBridgeListEvents({
    required ThingdBridge that,
    required String stream,
  });

  Future<ThingdBridge> crateApiBridgeThingdBridgeOpen({required String path});

  Future<String> crateApiBridgeThingdBridgePutObject({
    required ThingdBridge that,
    required String collection,
    required String id,
    required String body,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ThingdBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ThingdBridge;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ThingdBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiBridgeThingdBridgeAppendEvent({
    required ThingdBridge that,
    required String stream,
    required String eventType,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeAppendEventConstMeta,
        argValues: [that, stream, eventType, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeAppendEventConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_append_event",
        argNames: ["that", "stream", "eventType", "body"],
      );

  @override
  Future<String?> crateApiBridgeThingdBridgeDeleteLastEvent({
    required ThingdBridge that,
    required String stream,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteLastEventConstMeta,
        argValues: [that, stream],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteLastEventConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_last_event",
        argNames: ["that", "stream"],
      );

  @override
  Future<bool> crateApiBridgeThingdBridgeDeleteObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteObjectConstMeta,
        argValues: [that, collection, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteObjectConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_object",
        argNames: ["that", "collection", "id"],
      );

  @override
  Future<BigInt> crateApiBridgeThingdBridgeDeleteStream({
    required ThingdBridge that,
    required String stream,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteStreamConstMeta,
        argValues: [that, stream],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteStreamConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_stream",
        argNames: ["that", "stream"],
      );

  @override
  Future<String?> crateApiBridgeThingdBridgeGetObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeGetObjectConstMeta,
        argValues: [that, collection, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeGetObjectConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_get_object",
        argNames: ["that", "collection", "id"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeListEvents({
    required ThingdBridge that,
    required String stream,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeListEventsConstMeta,
        argValues: [that, stream],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeListEventsConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_list_events",
        argNames: ["that", "stream"],
      );

  @override
  Future<ThingdBridge> crateApiBridgeThingdBridgeOpen({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeOpenConstMeta =>
      const TaskConstMeta(debugName: "ThingdBridge_open", argNames: ["path"]);

  @override
  Future<String> crateApiBridgeThingdBridgePutObject({
    required ThingdBridge that,
    required String collection,
    required String id,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgePutObjectConstMeta,
        argValues: [that, collection, id, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgePutObjectConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_put_object",
        argNames: ["that", "collection", "id", "body"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ThingdBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ThingdBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge;

  @protected
  ThingdBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ThingdBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ThingdBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ThingdBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ThingdBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ThingdBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    ThingdBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ThingdBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    ThingdBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ThingdBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    ThingdBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ThingdBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ThingdBridgeImpl extends RustOpaque implements ThingdBridge {
  // Not to be used by end users
  ThingdBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ThingdBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ThingdBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ThingdBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ThingdBridgePtr,
  );

  /// Append an event to a stream. Returns the stored event body.
  Future<String> appendEvent({
    required String stream,
    required String eventType,
    required String body,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeAppendEvent(
    that: this,
    stream: stream,
    eventType: eventType,
    body: body,
  );

  /// Delete the most recent event from a stream.
  /// Returns the deleted event body, or None if the stream was empty.
  Future<String?> deleteLastEvent({required String stream}) => RustLib
      .instance
      .api
      .crateApiBridgeThingdBridgeDeleteLastEvent(that: this, stream: stream);

  /// Delete an object by collection and id. Returns true if deleted.
  Future<bool> deleteObject({required String collection, required String id}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeDeleteObject(
        that: this,
        collection: collection,
        id: id,
      );

  /// Delete all events in a stream. Returns the count of deleted events.
  Future<BigInt> deleteStream({required String stream}) => RustLib.instance.api
      .crateApiBridgeThingdBridgeDeleteStream(that: this, stream: stream);

  /// Read an object by collection and id. Returns None if not found.
  Future<String?> getObject({required String collection, required String id}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeGetObject(
        that: this,
        collection: collection,
        id: id,
      );

  /// List all events in a stream, in ascending sequence order.
  Future<List<String>> listEvents({required String stream}) => RustLib
      .instance
      .api
      .crateApiBridgeThingdBridgeListEvents(that: this, stream: stream);

  /// Insert or replace an object. Returns the stored body.
  Future<String> putObject({
    required String collection,
    required String id,
    required String body,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgePutObject(
    that: this,
    collection: collection,
    id: id,
    body: body,
  );
}
