// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -426685290;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_local_dart_scorer',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiBridgeThingdBridgeAckJob({
    required ThingdBridge that,
    required String queue,
    required String jobId,
  });

  Future<String> crateApiBridgeThingdBridgeAggregate({
    required ThingdBridge that,
    required String collection,
    required String params,
  });

  Future<String> crateApiBridgeThingdBridgeAppendEvent({
    required ThingdBridge that,
    required String stream,
    required String eventType,
    required String body,
  });

  Future<List<String>> crateApiBridgeThingdBridgeAppendEventsBatch({
    required ThingdBridge that,
    required String stream,
    required List<(String, String)> events,
  });

  Future<String> crateApiBridgeThingdBridgeClaimJob({
    required ThingdBridge that,
    required String queue,
    required BigInt leaseMs,
  });

  Future<BigInt> crateApiBridgeThingdBridgeCountLinks({
    required ThingdBridge that,
  });

  Future<String> crateApiBridgeThingdBridgeCreateLink({
    required ThingdBridge that,
    required String fromRef,
    required String linkType,
    required String toRef,
  });

  Future<String?> crateApiBridgeThingdBridgeDeleteLastEvent({
    required ThingdBridge that,
    required String stream,
  });

  Future<bool> crateApiBridgeThingdBridgeDeleteLink({
    required ThingdBridge that,
    required String id,
  });

  Future<bool> crateApiBridgeThingdBridgeDeleteObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  });

  Future<BigInt> crateApiBridgeThingdBridgeDeleteObjectsBatch({
    required ThingdBridge that,
    required List<(String, String)> keys,
  });

  Future<BigInt> crateApiBridgeThingdBridgeDeleteStream({
    required ThingdBridge that,
    required String stream,
  });

  Future<List<String>> crateApiBridgeThingdBridgeGetNeighbors({
    required ThingdBridge that,
    required String reference,
    required String direction,
    String? linkType,
  });

  Future<String?> crateApiBridgeThingdBridgeGetObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  });

  Future<List<String>> crateApiBridgeThingdBridgeListDeadJobs({
    required ThingdBridge that,
    required String queue,
  });

  Future<List<String>> crateApiBridgeThingdBridgeListEvents({
    required ThingdBridge that,
    required String stream,
  });

  Future<List<(String, BigInt)>> crateApiBridgeThingdBridgeListEventsFrom({
    required ThingdBridge that,
    required String stream,
    required BigInt fromSequence,
    required BigInt limit,
  });

  Future<List<String>> crateApiBridgeThingdBridgeListJobs({
    required ThingdBridge that,
    required String queue,
  });

  Future<List<(String, String)>> crateApiBridgeThingdBridgeListObjects({
    required ThingdBridge that,
    required String collection,
    required BigInt limit,
    required BigInt offset,
  });

  Future<bool> crateApiBridgeThingdBridgeNackJob({
    required ThingdBridge that,
    required String queue,
    required String jobId,
    required BigInt delayMs,
    required String error,
  });

  Future<ThingdBridge> crateApiBridgeThingdBridgeOpen({required String path});

  Future<void> crateApiBridgeThingdBridgeOptimizeSearchIndex({
    required ThingdBridge that,
  });

  Future<String> crateApiBridgeThingdBridgePushJob({
    required ThingdBridge that,
    required String queue,
    required String jobId,
    required String body,
    required int maxAttempts,
  });

  Future<String> crateApiBridgeThingdBridgePutObject({
    required ThingdBridge that,
    required String collection,
    required String id,
    required String body,
  });

  Future<List<String>> crateApiBridgeThingdBridgePutObjectsBatch({
    required ThingdBridge that,
    required List<(String, String, String)> objects,
  });

  Future<List<String>> crateApiBridgeThingdBridgeSearch({
    required ThingdBridge that,
    required String query,
    required String collection,
    required BigInt limit,
  });

  Future<String> crateApiBridgeThingdBridgeTimeseries({
    required ThingdBridge that,
    required String collection,
    required String params,
  });

  Future<(int, int)> crateApiBridgeThingdBridgeWalCheckpoint({
    required ThingdBridge that,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ThingdBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ThingdBridge;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ThingdBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiBridgeThingdBridgeAckJob({
    required ThingdBridge that,
    required String queue,
    required String jobId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(queue, serializer);
          sse_encode_String(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeAckJobConstMeta,
        argValues: [that, queue, jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeAckJobConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_ack_job",
        argNames: ["that", "queue", "jobId"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgeAggregate({
    required ThingdBridge that,
    required String collection,
    required String params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeAggregateConstMeta,
        argValues: [that, collection, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeAggregateConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_aggregate",
        argNames: ["that", "collection", "params"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgeAppendEvent({
    required ThingdBridge that,
    required String stream,
    required String eventType,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeAppendEventConstMeta,
        argValues: [that, stream, eventType, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeAppendEventConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_append_event",
        argNames: ["that", "stream", "eventType", "body"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeAppendEventsBatch({
    required ThingdBridge that,
    required String stream,
    required List<(String, String)> events,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          sse_encode_list_record_string_string(events, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeAppendEventsBatchConstMeta,
        argValues: [that, stream, events],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeAppendEventsBatchConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_append_events_batch",
        argNames: ["that", "stream", "events"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgeClaimJob({
    required ThingdBridge that,
    required String queue,
    required BigInt leaseMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(queue, serializer);
          sse_encode_u_64(leaseMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeClaimJobConstMeta,
        argValues: [that, queue, leaseMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeClaimJobConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_claim_job",
        argNames: ["that", "queue", "leaseMs"],
      );

  @override
  Future<BigInt> crateApiBridgeThingdBridgeCountLinks({
    required ThingdBridge that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeCountLinksConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeCountLinksConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_count_links",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgeCreateLink({
    required ThingdBridge that,
    required String fromRef,
    required String linkType,
    required String toRef,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(fromRef, serializer);
          sse_encode_String(linkType, serializer);
          sse_encode_String(toRef, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeCreateLinkConstMeta,
        argValues: [that, fromRef, linkType, toRef],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeCreateLinkConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_create_link",
        argNames: ["that", "fromRef", "linkType", "toRef"],
      );

  @override
  Future<String?> crateApiBridgeThingdBridgeDeleteLastEvent({
    required ThingdBridge that,
    required String stream,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteLastEventConstMeta,
        argValues: [that, stream],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteLastEventConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_last_event",
        argNames: ["that", "stream"],
      );

  @override
  Future<bool> crateApiBridgeThingdBridgeDeleteLink({
    required ThingdBridge that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteLinkConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteLinkConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_link",
        argNames: ["that", "id"],
      );

  @override
  Future<bool> crateApiBridgeThingdBridgeDeleteObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteObjectConstMeta,
        argValues: [that, collection, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteObjectConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_object",
        argNames: ["that", "collection", "id"],
      );

  @override
  Future<BigInt> crateApiBridgeThingdBridgeDeleteObjectsBatch({
    required ThingdBridge that,
    required List<(String, String)> keys,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_list_record_string_string(keys, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteObjectsBatchConstMeta,
        argValues: [that, keys],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteObjectsBatchConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_objects_batch",
        argNames: ["that", "keys"],
      );

  @override
  Future<BigInt> crateApiBridgeThingdBridgeDeleteStream({
    required ThingdBridge that,
    required String stream,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeDeleteStreamConstMeta,
        argValues: [that, stream],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeDeleteStreamConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_delete_stream",
        argNames: ["that", "stream"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeGetNeighbors({
    required ThingdBridge that,
    required String reference,
    required String direction,
    String? linkType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(reference, serializer);
          sse_encode_String(direction, serializer);
          sse_encode_opt_String(linkType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeGetNeighborsConstMeta,
        argValues: [that, reference, direction, linkType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeGetNeighborsConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_get_neighbors",
        argNames: ["that", "reference", "direction", "linkType"],
      );

  @override
  Future<String?> crateApiBridgeThingdBridgeGetObject({
    required ThingdBridge that,
    required String collection,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeGetObjectConstMeta,
        argValues: [that, collection, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeGetObjectConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_get_object",
        argNames: ["that", "collection", "id"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeListDeadJobs({
    required ThingdBridge that,
    required String queue,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(queue, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeListDeadJobsConstMeta,
        argValues: [that, queue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeListDeadJobsConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_list_dead_jobs",
        argNames: ["that", "queue"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeListEvents({
    required ThingdBridge that,
    required String stream,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeListEventsConstMeta,
        argValues: [that, stream],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeListEventsConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_list_events",
        argNames: ["that", "stream"],
      );

  @override
  Future<List<(String, BigInt)>> crateApiBridgeThingdBridgeListEventsFrom({
    required ThingdBridge that,
    required String stream,
    required BigInt fromSequence,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(stream, serializer);
          sse_encode_u_64(fromSequence, serializer);
          sse_encode_u_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_string_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeListEventsFromConstMeta,
        argValues: [that, stream, fromSequence, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeListEventsFromConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_list_events_from",
        argNames: ["that", "stream", "fromSequence", "limit"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeListJobs({
    required ThingdBridge that,
    required String queue,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(queue, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeListJobsConstMeta,
        argValues: [that, queue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeListJobsConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_list_jobs",
        argNames: ["that", "queue"],
      );

  @override
  Future<List<(String, String)>> crateApiBridgeThingdBridgeListObjects({
    required ThingdBridge that,
    required String collection,
    required BigInt limit,
    required BigInt offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_u_64(limit, serializer);
          sse_encode_u_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_string_string,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeListObjectsConstMeta,
        argValues: [that, collection, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeListObjectsConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_list_objects",
        argNames: ["that", "collection", "limit", "offset"],
      );

  @override
  Future<bool> crateApiBridgeThingdBridgeNackJob({
    required ThingdBridge that,
    required String queue,
    required String jobId,
    required BigInt delayMs,
    required String error,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(queue, serializer);
          sse_encode_String(jobId, serializer);
          sse_encode_u_64(delayMs, serializer);
          sse_encode_String(error, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeNackJobConstMeta,
        argValues: [that, queue, jobId, delayMs, error],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeNackJobConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_nack_job",
        argNames: ["that", "queue", "jobId", "delayMs", "error"],
      );

  @override
  Future<ThingdBridge> crateApiBridgeThingdBridgeOpen({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeOpenConstMeta =>
      const TaskConstMeta(debugName: "ThingdBridge_open", argNames: ["path"]);

  @override
  Future<void> crateApiBridgeThingdBridgeOptimizeSearchIndex({
    required ThingdBridge that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeOptimizeSearchIndexConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeOptimizeSearchIndexConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_optimize_search_index",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgePushJob({
    required ThingdBridge that,
    required String queue,
    required String jobId,
    required String body,
    required int maxAttempts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(queue, serializer);
          sse_encode_String(jobId, serializer);
          sse_encode_String(body, serializer);
          sse_encode_u_32(maxAttempts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgePushJobConstMeta,
        argValues: [that, queue, jobId, body, maxAttempts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgePushJobConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_push_job",
        argNames: ["that", "queue", "jobId", "body", "maxAttempts"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgePutObject({
    required ThingdBridge that,
    required String collection,
    required String id,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgePutObjectConstMeta,
        argValues: [that, collection, id, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgePutObjectConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_put_object",
        argNames: ["that", "collection", "id", "body"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgePutObjectsBatch({
    required ThingdBridge that,
    required List<(String, String, String)> objects,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_list_record_string_string_string(objects, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgePutObjectsBatchConstMeta,
        argValues: [that, objects],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgePutObjectsBatchConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_put_objects_batch",
        argNames: ["that", "objects"],
      );

  @override
  Future<List<String>> crateApiBridgeThingdBridgeSearch({
    required ThingdBridge that,
    required String query,
    required String collection,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_String(collection, serializer);
          sse_encode_u_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeSearchConstMeta,
        argValues: [that, query, collection, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeSearchConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_search",
        argNames: ["that", "query", "collection", "limit"],
      );

  @override
  Future<String> crateApiBridgeThingdBridgeTimeseries({
    required ThingdBridge that,
    required String collection,
    required String params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          sse_encode_String(collection, serializer);
          sse_encode_String(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeTimeseriesConstMeta,
        argValues: [that, collection, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeTimeseriesConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_timeseries",
        argNames: ["that", "collection", "params"],
      );

  @override
  Future<(int, int)> crateApiBridgeThingdBridgeWalCheckpoint({
    required ThingdBridge that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_i_32_i_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBridgeThingdBridgeWalCheckpointConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeThingdBridgeWalCheckpointConstMeta =>
      const TaskConstMeta(
        debugName: "ThingdBridge_wal_checkpoint",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ThingdBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ThingdBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge;

  @protected
  ThingdBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ThingdBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ThingdBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<(String, String, String)> dco_decode_list_record_string_string_string(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_string_string)
        .toList();
  }

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_u_64).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (int, int) dco_decode_record_i_32_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_i_32(arr[0]), dco_decode_i_32(arr[1]));
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  (String, String, String) dco_decode_record_string_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
      dco_decode_String(arr[2]),
    );
  }

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_u_64(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ThingdBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ThingdBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ThingdBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ThingdBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String, String)> sse_decode_list_record_string_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, BigInt)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_u_64(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int) sse_decode_record_i_32_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_32(deserializer);
    var var_field1 = sse_decode_i_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String, String) sse_decode_record_string_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    var var_field2 = sse_decode_String(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_u_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    ThingdBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ThingdBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    ThingdBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ThingdBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThingdBridge(
    ThingdBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ThingdBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string_string(
    List<(String, String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_u_64(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_u_64(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_i_32_i_32((int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.$1, serializer);
    sse_encode_i_32(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string_string(
    (String, String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
    sse_encode_String(self.$3, serializer);
  }

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_u_64(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ThingdBridgeImpl extends RustOpaque implements ThingdBridge {
  // Not to be used by end users
  ThingdBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ThingdBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ThingdBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ThingdBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ThingdBridgePtr,
  );

  /// Acknowledge a leased job as completed. Returns true if acked.
  Future<bool> ackJob({required String queue, required String jobId}) => RustLib
      .instance
      .api
      .crateApiBridgeThingdBridgeAckJob(that: this, queue: queue, jobId: jobId);

  /// Run an aggregation over a collection.
  ///
  /// `params` is a JSON string:
  ///   { "function": "count|sum|avg|min|max",
  ///     "field": "...", "groupBy": "..." }
  /// Returns JSON result with total and groups.
  Future<String> aggregate({
    required String collection,
    required String params,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeAggregate(
    that: this,
    collection: collection,
    params: params,
  );

  /// Append an event to a stream. Returns the stored event body.
  Future<String> appendEvent({
    required String stream,
    required String eventType,
    required String body,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeAppendEvent(
    that: this,
    stream: stream,
    eventType: eventType,
    body: body,
  );

  /// Append multiple events to a stream in a single transaction.
  Future<List<String>> appendEventsBatch({
    required String stream,
    required List<(String, String)> events,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeAppendEventsBatch(
    that: this,
    stream: stream,
    events: events,
  );

  /// Claim the next ready job from a queue. Returns JSON or empty string.
  ///
  /// Returns JSON with id, queue, body, status, attempts.
  /// Returns empty string if no job available.
  Future<String> claimJob({required String queue, required BigInt leaseMs}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeClaimJob(
        that: this,
        queue: queue,
        leaseMs: leaseMs,
      );

  /// Count total links.
  Future<BigInt> countLinks() =>
      RustLib.instance.api.crateApiBridgeThingdBridgeCountLinks(that: this);

  /// Create a directed link between two references. Returns the link id.
  Future<String> createLink({
    required String fromRef,
    required String linkType,
    required String toRef,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeCreateLink(
    that: this,
    fromRef: fromRef,
    linkType: linkType,
    toRef: toRef,
  );

  /// Delete the most recent event from a stream.
  Future<String?> deleteLastEvent({required String stream}) => RustLib
      .instance
      .api
      .crateApiBridgeThingdBridgeDeleteLastEvent(that: this, stream: stream);

  /// Delete a link by id. Returns true if deleted.
  Future<bool> deleteLink({required String id}) => RustLib.instance.api
      .crateApiBridgeThingdBridgeDeleteLink(that: this, id: id);

  /// Delete an object by collection and id. Returns true if deleted.
  Future<bool> deleteObject({required String collection, required String id}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeDeleteObject(
        that: this,
        collection: collection,
        id: id,
      );

  /// Delete multiple objects in a single transaction. Returns count deleted.
  Future<BigInt> deleteObjectsBatch({required List<(String, String)> keys}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeDeleteObjectsBatch(
        that: this,
        keys: keys,
      );

  /// Delete all events in a stream. Returns the count of deleted events.
  Future<BigInt> deleteStream({required String stream}) => RustLib.instance.api
      .crateApiBridgeThingdBridgeDeleteStream(that: this, stream: stream);

  /// Get neighbors of a reference. Returns JSON array of links.
  ///
  /// `direction`: "Outgoing", "Incoming", or "Both" (default).
  /// `link_type`: optional filter.
  Future<List<String>> getNeighbors({
    required String reference,
    required String direction,
    String? linkType,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeGetNeighbors(
    that: this,
    reference: reference,
    direction: direction,
    linkType: linkType,
  );

  /// Read an object by collection and id. Returns None if not found.
  Future<String?> getObject({required String collection, required String id}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeGetObject(
        that: this,
        collection: collection,
        id: id,
      );

  /// List dead-letter jobs in a queue. Returns JSON array.
  Future<List<String>> listDeadJobs({required String queue}) => RustLib
      .instance
      .api
      .crateApiBridgeThingdBridgeListDeadJobs(that: this, queue: queue);

  /// List all events in a stream, in ascending sequence order.
  Future<List<String>> listEvents({required String stream}) => RustLib
      .instance
      .api
      .crateApiBridgeThingdBridgeListEvents(that: this, stream: stream);

  /// List events from a given sequence number. Returns (body, sequence) pairs.
  Future<List<(String, BigInt)>> listEventsFrom({
    required String stream,
    required BigInt fromSequence,
    required BigInt limit,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeListEventsFrom(
    that: this,
    stream: stream,
    fromSequence: fromSequence,
    limit: limit,
  );

  /// List all jobs in a queue. Returns JSON array.
  Future<List<String>> listJobs({required String queue}) => RustLib.instance.api
      .crateApiBridgeThingdBridgeListJobs(that: this, queue: queue);

  /// List all object IDs in a collection. Returns (id, body) pairs.
  /// `limit` max results (0 for all). `offset` for pagination.
  Future<List<(String, String)>> listObjects({
    required String collection,
    required BigInt limit,
    required BigInt offset,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeListObjects(
    that: this,
    collection: collection,
    limit: limit,
    offset: offset,
  );

  /// Reject a leased job for retry or dead-letter routing.
  Future<bool> nackJob({
    required String queue,
    required String jobId,
    required BigInt delayMs,
    required String error,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeNackJob(
    that: this,
    queue: queue,
    jobId: jobId,
    delayMs: delayMs,
    error: error,
  );

  /// Optimize the FTS5 search index to merge segments.
  Future<void> optimizeSearchIndex() => RustLib.instance.api
      .crateApiBridgeThingdBridgeOptimizeSearchIndex(that: this);

  /// Push a job onto a queue. Returns the job id.
  ///
  /// `body` is the job payload as a JSON string.
  /// `max_attempts` is the max retry count before dead-letter.
  /// If `job_id` is empty, one is auto-generated.
  Future<String> pushJob({
    required String queue,
    required String jobId,
    required String body,
    required int maxAttempts,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgePushJob(
    that: this,
    queue: queue,
    jobId: jobId,
    body: body,
    maxAttempts: maxAttempts,
  );

  /// Insert or replace an object. Returns the stored body.
  Future<String> putObject({
    required String collection,
    required String id,
    required String body,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgePutObject(
    that: this,
    collection: collection,
    id: id,
    body: body,
  );

  /// Insert or replace multiple objects in a single transaction.
  Future<List<String>> putObjectsBatch({
    required List<(String, String, String)> objects,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgePutObjectsBatch(
    that: this,
    objects: objects,
  );

  /// Full-text search across objects and events.
  ///
  /// Returns JSON array of search hits with id, collection, text, score, kind.
  Future<List<String>> search({
    required String query,
    required String collection,
    required BigInt limit,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeSearch(
    that: this,
    query: query,
    collection: collection,
    limit: limit,
  );

  /// Run a time-bucketed aggregation.
  ///
  /// `params` is a JSON string:
  ///   { "function": "...", "field": "...",
  ///     "bucket": "hour|day|week|month",
  ///     "from": "ISO8601", "to": "ISO8601" }
  Future<String> timeseries({
    required String collection,
    required String params,
  }) => RustLib.instance.api.crateApiBridgeThingdBridgeTimeseries(
    that: this,
    collection: collection,
    params: params,
  );

  /// Flush the SQLite WAL into the main database file.
  Future<(int, int)> walCheckpoint() =>
      RustLib.instance.api.crateApiBridgeThingdBridgeWalCheckpoint(that: this);
}
