#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  setup-cloud.sh — One-time thingd.cloud API key setup
#
#  Prerequisites: Node.js >= 24.0.0, npm
#
#  This script:
#    1. Ensures @thingd/cli is installed
#    2. Authenticates with thingd.cloud (opens browser)
#    3. Creates a named API token for DartCam
#    4. Writes the token into .env for --dart-define-from-file
#
#  Run once per developer machine.
# ─────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

echo "==> Checking for @thingd/cli..."
if ! npx @thingd/cli --version &>/dev/null; then
  echo "    Installing @thingd/cli globally..."
  npm install -g @thingd/cli
fi

echo ""
echo "==> Authenticating with thingd.cloud..."
echo "    (a browser window will open for device-code login)"
npx @thingd/cli cloud login
echo "    ✓ Authenticated"

echo ""
echo "==> Creating an API token for DartCam..."
read -r -p "    Token name [dartcam]: " TOKEN_NAME
TOKEN_NAME="${TOKEN_NAME:-dartcam}"

TOKEN=$(npx @thingd/cli cloud token create "$TOKEN_NAME" 2>&1 | tail -1)
echo "    ✓ Token created"

cat > "$ENV_FILE" <<ENVEOF
# thingd.cloud configuration
# Auto-generated by scripts/setup-cloud.sh on $(date)
THINGD_CLOUD_URL=https://api.thingd.cloud
THINGD_CLOUD_API_KEY=$TOKEN
ENVEOF

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✓ thingd.cloud credentials written to .env         ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Next steps:                                        ║"
echo "║                                                     ║"
echo "║  flutter build apk --release --dart-define-from-file=.env  ║"
echo "║                                                     ║"
echo "║  Or for debug:                                      ║"
echo "║  flutter run --dart-define-from-file=.env           ║"
echo "╚══════════════════════════════════════════════════════╝"
