// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ThingdBridge>>
abstract class ThingdBridge implements RustOpaqueInterface {
  /// Append an event to a stream. Returns the stored event body.
  Future<String> appendEvent({
    required String stream,
    required String eventType,
    required String body,
  });

  /// Delete the most recent event from a stream.
  /// Returns the deleted event body, or None if the stream was empty.
  Future<String?> deleteLastEvent({required String stream});

  /// Delete an object by collection and id. Returns true if deleted.
  Future<bool> deleteObject({required String collection, required String id});

  /// Delete all events in a stream. Returns the count of deleted events.
  Future<BigInt> deleteStream({required String stream});

  /// Read an object by collection and id. Returns None if not found.
  Future<String?> getObject({required String collection, required String id});

  /// List all events in a stream, in ascending sequence order.
  Future<List<String>> listEvents({required String stream});

  /// Open or create a thingd store at the given file path.
  static Future<ThingdBridge> open({required String path}) =>
      RustLib.instance.api.crateApiBridgeThingdBridgeOpen(path: path);

  /// Insert or replace an object. Returns the stored body.
  Future<String> putObject({
    required String collection,
    required String id,
    required String body,
  });
}
